name: Deploy Vince Stack

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create/Update deploy branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -B deploy
          git push origin deploy --force

      - name: Trigger Portainer Redeploy Webhook
        uses: distributhor/workflow-webhook@2381f0e9c7b6bf061fb1405bd0804b8706116369 # v3.0.8
        with:
          webhook_url: ${{ secrets.PORTAINER_REDEPLOY_HOOK }}
          webhook_secret: "trigger"
